apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: api-gateway
      context: backend/api-gateway
    - image: canonical-layer
      context: backend/services/canonical-layer
    - image: ml-persistence
      context: ml/jobs/persistence
    - image: ml-transcript-nlp
      context: ml/jobs/transcript-nlp
  googleCloudBuild:
    projectId: ${GCP_PROJECT_SHARED}
    diskSizeGb: 100
    machineType: E2_HIGHCPU_8
    timeout: 3600s
manifests:
  kustomize:
    paths:
      - k8s/overlays/{{.ENV}}
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - env: ENV=dev
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev
  - name: staging
    activation:
      - env: ENV=staging
    manifests:
      kustomize:
        paths:
          - k8s/overlays/staging
  - name: production
    activation:
      - env: ENV=production
    manifests:
      kustomize:
        paths:
          - k8s/overlays/production
